CREATE TABLE IF NOT EXISTS ISSUE (
  seq     INT PRIMARY KEY AUTO_INCREMENT,
  title   VARCHAR(1000) NOT NULL,
  content VARCHAR(4000) NOT NULL,
  step    VARCHAR(20)   NOT NULL,
  del     INT             DEFAULT 0
);


CREATE TABLE IF NOT EXISTS ENUSER (
  id       VARCHAR(100) PRIMARY KEY,
  pwd      VARCHAR(2048) NOT NULL,
  name     VARCHAR(20)   NOT NULL,
  position VARCHAR(20)   NOT NULL,
  email    VARCHAR(50)   NOT NULL

);

CREATE TABLE IF NOT EXISTS ISSUEFILE (
  seq      INT PRIMARY KEY         AUTO_INCREMENT,
  pseq     INT REFERENCES ISSUE (seq),
  filename VARCHAR(100) NOT NULL,
  path     VARCHAR(500) NOT NULL   DEFAULT 0,
  rdate    DATE         NOT NULL
);
/*
DROP TABLE ISSUE;
DROP TABLE ENUSER;
DROP TABLE ISSUEFILE;*/